### ISSUE TITLE
生成的文件提示错误，具体如下；

### ISSUE THREAD

**Issue by justincnn** [whoisix/subscribe2clash#7]
proxy group[0]: `use` or `proxies` missing

**Comment by whoisix** [comment]
策略组没有节点。

如果有自己改过策略组配置，需要在配置的策略中写入` - "1"`项，这样才会把解析出来的节点写入该策略组。

```
  - name: 节点选择
    type: select  
    proxies:  
      - ✈ 延迟最低  
      - ✈ 手动选择  
      - ✈ 故障切换  
      - DIRECT  
      - "1"
```
